export type Profession =
  | 'Software'
  | 'Accounting'
  | 'Marketing'
  | 'Engineering'
  | 'Healthcare'
  | 'Graduate';

export type Sample = {
  id: string;
  title: string;
  profession: Profession;
  type: 'Portfolio' | 'CV';
  summary: string;
  /** The sample page: /portfolio/<slug>/ or /cv/<slug>/. */
  href: string;
  /** Card thumbnail in /public/samples, generated by `npm run previews`. */
  image: string;
  /** Full-size preview shown when the thumbnail is clicked. */
  preview: string;
  /** For CVs, the downloadable PDF. */
  pdf?: string;
  result?: string;
};

export const professions: Profession[] = [
  'Software',
  'Accounting',
  'Marketing',
  'Engineering',
  'Healthcare',
  'Graduate',
];

/**
 * The gallery. Every entry points at a real sample page in this site, and its
 * images are screenshots of that page — regenerate them with `npm run previews`
 * after changing content/portfolios.ts or content/cvs.ts.
 */
export const samples: Sample[] = [
  {
    id: 'portfolio-software',
    title: 'Full-stack developer portfolio',
    profession: 'Software',
    type: 'Portfolio',
    summary:
      'Single-page portfolio with project case studies, a skills matrix and a contact form. Loads in under a second on 4G.',
    href: '/portfolio/software-developer/',
    image: '/samples/portfolio-software-developer.jpg',
    preview: '/samples/portfolio-software-developer-full.jpg',
    result: 'Built in 6 days',
  },
  {
    id: 'portfolio-marketing',
    title: 'Digital marketer portfolio',
    profession: 'Marketing',
    type: 'Portfolio',
    summary:
      'Campaign results front and centre, with before-and-after metrics and downloadable case studies.',
    href: '/portfolio/digital-marketer/',
    image: '/samples/portfolio-digital-marketer.jpg',
    preview: '/samples/portfolio-digital-marketer-full.jpg',
    result: 'Built in 7 days',
  },
  {
    id: 'portfolio-engineering',
    title: 'Civil engineer portfolio',
    profession: 'Engineering',
    type: 'Portfolio',
    summary:
      'Project gallery with site photographs, drawings and a clear certification timeline.',
    href: '/portfolio/civil-engineer/',
    image: '/samples/portfolio-civil-engineer.jpg',
    preview: '/samples/portfolio-civil-engineer-full.jpg',
    result: 'Built in 8 days',
  },
  {
    id: 'portfolio-accounting',
    title: 'Senior accountant portfolio',
    profession: 'Accounting',
    type: 'Portfolio',
    summary:
      'Finance-first layout: close timelines, controls work and cash released, with the numbers leading each entry.',
    href: '/portfolio/senior-accountant/',
    image: '/samples/portfolio-senior-accountant.jpg',
    preview: '/samples/portfolio-senior-accountant-full.jpg',
    result: 'Built in 7 days',
  },
  {
    id: 'portfolio-healthcare',
    title: 'ICU nurse portfolio',
    profession: 'Healthcare',
    type: 'Portfolio',
    summary:
      'Structured for overseas recruiters — registrations, clinical competencies and language scores above the fold.',
    href: '/portfolio/registered-nurse/',
    image: '/samples/portfolio-registered-nurse.jpg',
    preview: '/samples/portfolio-registered-nurse-full.jpg',
    result: 'Built in 6 days',
  },
  {
    id: 'portfolio-graduate',
    title: 'Fresh graduate portfolio',
    profession: 'Graduate',
    type: 'Portfolio',
    summary:
      'No employment history to lead with, so projects, an internship and coursework carry the page instead.',
    href: '/portfolio/graduate/',
    image: '/samples/portfolio-graduate.jpg',
    preview: '/samples/portfolio-graduate-full.jpg',
    result: 'Built in 5 days',
  },
  {
    id: 'cv-senior-accountant',
    title: 'Senior accountant CV',
    profession: 'Accounting',
    type: 'CV',
    summary:
      'Classic layout. Serif name, ruled sections and a single column — the safest shape for applicant tracking systems.',
    href: '/cv/senior-accountant/',
    image: '/samples/cv-senior-accountant.jpg',
    preview: '/samples/cv-senior-accountant-full.jpg',
    pdf: '/samples/cv-senior-accountant.pdf',
    result: '3 interviews in 4 weeks',
  },
  {
    id: 'cv-software-engineer',
    title: 'Software engineer CV',
    profession: 'Software',
    type: 'CV',
    summary:
      'Modern layout. Headline numbers up top, skills grouped in a tinted sidebar, the story in the main column.',
    href: '/cv/software-engineer/',
    image: '/samples/cv-software-engineer.jpg',
    preview: '/samples/cv-software-engineer-full.jpg',
    pdf: '/samples/cv-software-engineer.pdf',
    result: '2 offers in 6 weeks',
  },
  {
    id: 'cv-digital-marketer',
    title: 'Digital marketer CV',
    profession: 'Marketing',
    type: 'CV',
    summary:
      'Executive layout. A bold header band carries the three results a hiring manager should remember.',
    href: '/cv/digital-marketer/',
    image: '/samples/cv-digital-marketer.jpg',
    preview: '/samples/cv-digital-marketer-full.jpg',
    pdf: '/samples/cv-digital-marketer.pdf',
  },
  {
    id: 'cv-civil-engineer',
    title: 'Civil engineer CV',
    profession: 'Engineering',
    type: 'CV',
    summary:
      'Classic layout. Chartership, contract forms and project values placed where a recruiter scans first.',
    href: '/cv/civil-engineer/',
    image: '/samples/cv-civil-engineer.jpg',
    preview: '/samples/cv-civil-engineer-full.jpg',
    pdf: '/samples/cv-civil-engineer.pdf',
  },
  {
    id: 'cv-registered-nurse',
    title: 'Registered nurse CV',
    profession: 'Healthcare',
    type: 'CV',
    summary:
      'Executive layout. NMC registration, IELTS score and critical-care competencies above the fold for overseas applications.',
    href: '/cv/registered-nurse/',
    image: '/samples/cv-registered-nurse.jpg',
    preview: '/samples/cv-registered-nurse-full.jpg',
    pdf: '/samples/cv-registered-nurse.pdf',
    result: 'Shortlisted by 3 NHS trusts',
  },
  {
    id: 'cv-graduate',
    title: 'Fresh graduate CV',
    profession: 'Graduate',
    type: 'CV',
    summary:
      'Modern layout. No long work history, so GPA, the internship and a final-year project carry the page.',
    href: '/cv/graduate/',
    image: '/samples/cv-graduate.jpg',
    preview: '/samples/cv-graduate-full.jpg',
    pdf: '/samples/cv-graduate.pdf',
    result: 'First job offer in 5 weeks',
  },
];
